### ISSUE TITLE
Add syntax highlighting for  .class_modifier   and   .class_key_value  (with single underscores)

### ISSUE THREAD

**Issue by chepash** [joloyonaha/scss-bem-support#2]
I really like your plugin! I've been learning SASS on my own, and I'm glad I found your plugin as I couldn't find any alternatives. However, I noticed a minor issue with syntax highlighting.

For example, the following syntax is correctly highlighted:
`.block__element`
e.g.:
```
.header
.header__logo
```

It works well. However, when I use SASS, your plugin ignores other BEM syntax.
We were also taught BEM syntax like:
`.class_modifier` and `.class_key_value` (Single underscores are intentionally used)

For instance:
```
.header {
&_small { }
&_color_cyan { }
&_color_red { }
}
```

Unfortunately, your plugin doesn't highlight thisyntax. Could you please add syntax highlighting for these as well?

![image](https://user-images.githubusercontent.com/100382249/232557404-a6ec3f64-0423-4d87-8365-d1b9b155e723.png)

**Comment by chepash** [comment]
made a simple pull request

**Comment by joloyonaha** [comment]
Thanks! I'm not familiar with using BEM like `.class_modifier` and `.class_key_value`. Glad you brought that up. I merged your PR, will push an update to extension later.
